### ISSUE TITLE
Platform Volumes Z offset - [Grass Land Demo]

### ISSUE THREAD

**Issue by coderespawn** [coderespawn/dungeon-architect-ue4-issues#1]
Platform volumes have wrong z-offset in the statues in the grassland demo

Video: https://www.youtube.com/watch?v=qxfqK2djQnY&t=1m33s 
Skip to 1:33

Need to investigate if this is a code issue or incorrect z offset in the theme file

**Comment by GameMaster79** [comment]
Hi, if it helps your investigation, I noticed if you change the z scale of the platform volume that will resolve the issue. A z scale of .1 seemed to work.  Although, that might raise other issues down the road.  I don't know.   Thanks for looking into it.
