### ISSUE TITLE
Can't build for Linux on UE 4.20.1

### ISSUE THREAD

**Issue by Jau-Al** [coderespawn/dungeon-architect-ue4-issues#16]
Hello,
I downloaded (August 14th 2018) the last Dungeon Architect from Epic launcher on Windows.
I then copied the plugin in a dedicated projects, so that it would be compiled when opened on Linux (Ubuntu 18.04).

![capture d ecran de 2018-08-15 06-24-35](https://user-images.githubusercontent.com/15030964/44131530-ee75b13e-a053-11e8-8e49-12786c8b5485.png)

I opened Unreal Editor 4.20.1, opened the project. 
It started compiling then : 

![capture d ecran de 2018-08-15 06-18-11](https://user-images.githubusercontent.com/15030964/44131591-57f55c2c-a054-11e8-9b2b-5e33d2b67944.png)

Weird if the plugin compiled on Windows and Mac at Epic... 
Any idea ?

**Comment by LinuxDonald** [comment]
I had an problem too with dont compile on linux. I was something in the DungeonArchitect.uplugin

Could you please post the content of it than maybe i can help you

**Comment by Jau-Al** [comment]
No whit-list that could limit it to Windows or MacOS.
```
{
	"FileVersion": 3,
	"Version": 92,
	"VersionName": "2.9.2",
	"FriendlyName": "Dungeon Architect",
	"Description": "Build procedural dungeons",
	"Category": "Procedural",
	"CreatedBy": "Ali Akbar Vathi",
	"CreatedByURL": "http://coderespawn.com",
	"DocsURL": "",
	"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/1a4ad2a06f174a26af8a29728241ce42",
	"SupportURL": "",
	"EngineVersion": "4.20.0",
	"CanContainContent": true,
	"Installed": true,
	"Modules": [
		{
			"Name": "DungeonArchitectRuntime",
			"Type": "Runtime",
			"LoadingPhase": "PreDefault"
		},
		{
			"Name": "DungeonArchitectEditor",
			"Type": "Editor",
			"LoadingPhase": "Default"
		},
		{
			"Name": "DungeonArchitectHelpSystem",
			"Type": "Editor",
			"LoadingPhase": "Default"
		}
	],
	"Plugins": [
		{
			"Name": "ApexDestruction",
			"Enabled": true
		}
	]
}
```

**Comment by LinuxDonald** [comment]
I dont had any compile problems. I tested it now. Created an new Blueprint Project copied the Plugin into MyProject/Plugins and on start up it asked me if i want to compile the plugin. It worked without problems. I use UE4 4.20 branch.

**Comment by Jau-Al** [comment]
aaaaah I'm sorry ! 

Some time aga, before the plugin update, I tried compiling the previous version (for 4.19) in a project and with the whole engine. It failed.
It looks like I forgot to remove the files inside the engine. I removed everythinng, created a new empty project, added the plugin and it compiled. 

sryyyyy
