### ISSUE TITLE
Warnings when Packaging

### ISSUE THREAD

**Issue by kardmode** [coderespawn/dungeon-architect-ue4-issues#26]
Dungeon Architect v2.23.2
UE4.27.1

PackagingResults: Warning: ObjectProperty FMaterialOverride::Material is not initialized properly. Module:DungeonArchitectRuntime File:Public/Core/Actors/DungeonMesh.h
PackagingResults: Warning: ObjectProperty FDungeonMiniMapOverlayIcon::Icon is not initialized properly. Module:DungeonArchitectRuntime File:Public/Frameworks/MiniMap/DungeonMiniMap.h
PackagingResults: Warning: ObjectProperty FDungeonMarkerInfo::TemplateObject is not initialized properly. Module:DungeonArchitectRuntime File:Public/Core/DungeonModel.h
PackagingResults: Warning: ObjectProperty FSnapGridFlowModuleDatabaseConnectionInfo::ConnectionInfo is not initialized properly. Module:DungeonArchitectRuntime File:Public/Frameworks/Snap/SnapGridFlow/SnapGridFlowModuleDatabase.h
PackagingResults: Warning: ObjectProperty FSnapMapModuleDatabaseConnectionInfo::ConnectionInfo is not initialized properly. Module:DungeonArchitectRuntime File:Public/Frameworks/Snap/SnapMap/SnapMapModuleDatabase.h

**Comment by coderespawn** [comment]
Fixed
